### ISSUE TITLE
Upcoming Meeting Agenda - 24 Jan 2017

### ISSUE THREAD

**Issue by joehand** [datprotocol/working-group#1]
Please comment with proposed agenda items. Once a comment gets a +1 then I'll update this comment to include on the agenda.

[Meeting Notes](https://hackmd.io/EwYxBYFMDNkhaAzATmSe4Ds0CG8cAMO4G4AHAEYWK65kCsQA#)

### Proposed Agenda

- **JOE** Summary/Review of action items from previous meeting (#2)
- **BRYAN** Discussion and approval of DEP 1 (datprotocol/DEPs#2)
- **BRYAN** structure (how many DEPs) and division of labor for expressing existing protocol in DEP form
- **BRYAN** multi-writer API ergonomics (eg, making single-writer case simple)<sup id="a1">[1](#f1)</sup>
- **TARA** post-mortem of Dat discovery failing on 1/20, future for DHT<sup id="a2">[2](#f2)</sup>

##### Footnotes

<b id="f1">1</b> 

I was primarily thinking of API users. This is referring to the conversation we had about `get()` returning an array of values (potentially one from each writer, if there was a conflict), and leaving disambiguation to API callers. I think this might be reasonable from a modularity standpoint, but want to make sure that helpers exist somewhere so high-level app developers don't need to invent a disambiguation solution every time (unless they want to), or worse, do something trivial like take the first element of the array, which would work for single-writer but break in confusing ways later. [&#x21a9;](#a1)

<b id="f2">2</b>
* https://twitter.com/louiscenter/status/954973782229356544
* https://twitter.com/yhancik/status/954879519814574080
 [&#x21a9;](#a2)

**Comment by pfrazee** [comment]
Agenda item: Discussion and approval of DEP 1 (https://github.com/datprotocol/DEPs/pull/2)

**Comment by bnewbold** [comment]
Agenda item: structure (how many DEPs) and division of labor for expressing existing protocol in DEP form

**Comment by bnewbold** [comment]
Agenda item: multi-writer API ergonomics (eg, making single-writer case simple)

**Comment by bnewbold** [comment]
Agenda item: breaking change deployment logistics

**Comment by mafintosh** [comment]
>> Agenda item: multi-writer API ergonomics (eg, making single-writer case simple)

@bnewbold could you clarify if this is from an protocol implementers point of view or api user?

**Comment by bnewbold** [comment]
@mafintosh I was primarily thinking of API users. This is referring to the conversation we had about `get()` returning an array of values (potentially one from each writer, if there was a conflict), and leaving disambiguation to API callers. I think this might be reasonable from a modularity standpoint, but want to make sure that helpers exist somewhere so high-level app developers don't need to invent a disambiguation solution every time (unless they want to), or worse, do something trivial like take the first element of the array, which would work for single-writer but break in confusing ways later.

**Comment by joehand** [comment]
Incomplete action items from meeting 1 (#2)

**Comment by taravancil** [comment]
Agenda item: post-mortem of Dat discovery failing on 1/20, future for DHT

* https://twitter.com/louiscenter/status/954973782229356544
* https://twitter.com/yhancik/status/954879519814574080

**Comment by joehand** [comment]
Meeting finished, notes here: https://hackmd.io/EwYxBYFMDNkhaAzATmSe4Ds0CG8cAMO4G4AHAEYWK65kCsQA?edit
