### ISSUE TITLE
Upcoming Meeting Agenda - 4 Apr 2018

### ISSUE THREAD

**Issue by pfrazee** [datprotocol/working-group#12]
Please comment with proposed agenda items (start comment with AGENDA ITEM). Once a comment gets a +1 then I'll update this comment to include on the agenda.

### Proposed Agenda

 - AGENDA ITEM: What happened to concept of "checkpoints"? Is that an idea that is still being discussed or considered? I discussed this with @taravancil in irc yesterday and we decided to ask during the next meeting.
- AGENDA ITEM: discuss HTTP Pinning Service API DEP datprotocol/DEPs#19
- AGENDA ITEM: general DEP progress update. Timeline?
- AGENDA ITEM: process for handling security questions.

### Meetings Prep

- Before Meeting:
  - [ ] Create new meeting notes [file from template](https://github.com/datprotocol/working-group/blob/master/meeting-notes/NUM-DAYMONTHYEAR-TEMPLATE.md)
  - [ ] Add links to: agenda discussion, previous meeting action items, previous meeting notes
  - [ ] Put agenda in notes
- After Meeting:
  - [ ] Make [Action Items Issue](https://github.com/datprotocol/working-group/issues/new?template=meeting_actions.md), list action items
  - [ ] Commit meeting notes to working-group repo
  - [ ] Make [New Meeting Agenda Issue](https://github.com/datprotocol/working-group/issues/new?template=meeting_agenda.md)

**Comment by bcomnes** [comment]
Question:  What happened to concept of "checkpoints"?  Is that an idea that is still being discussed or considered? I discussed this with @taravancil in irc yesterday and we decided to ask during the next meeting.

**Comment by bcomnes** [comment]
> bnewbold_> I can't remember if there's a more formal security process, but I replied to this comment:
21:12 https://github.com/datproject/docs/issues/112
23:20 <mafintosh> Mathias Buus Thanks.
23:20 bnewbold_: we should set up a security mail
23:20 and a private repo for sec discussions

**Comment by joehand** [comment]
>  I can't remember if there's a more formal security process, but I replied to this comment:

Set up a repo and security@datproject.org. Action item is to add this to dat protocol.

AGENDA ITEM: process for handling security questions.

**Comment by pfrazee** [comment]
AGENDA ITEM: discuss HTTP Pinning Service API DEP https://github.com/datprotocol/DEPs/pull/19

**Comment by joehand** [comment]
AGENDA ITEM: general DEP progress update. Timeline?

**Comment by joehand** [comment]
Do we need to discuss the heartbeat issue? https://github.com/datprotocol/DEPs/issues/18
