### ISSUE TITLE
Action Items - Meeting #7 (4 Apr)

### ISSUE THREAD

**Issue by pfrazee** [datprotocol/working-group#15]
### Action items
Dat Protocol WG meeting **April 4, 2018** ([meeting notes](https://github.com/datprotocol/working-group/blob/master/meeting-notes/07-04apr2018.md))

- [x] Update Upcoming Meeting Agenda item template to specity that guests can't +1 agenda items. (@joehand)
* Security:
  - [ ] Add security email to the websites (@joehand, @pfrazee/@taravancil)
  - [ ] readmes of dat cli, dat-node (@joehand); beaker (@pfrazee/@taravancil)
  - [ ] Add info to issue template: "are you reporting a security issue that would impact general users? maybe try..." (@joehand); beaker (@pfrazee/@taravancil)
* HTTP Pin DEP
    - [x] Change `url` or `urls` in archive response (@pfrazee)
    - [x] Note that if quota==0 is a registry
    - [x] Use https://archive.org/services/purl/ for reltypes
* DEPs (from prev meeting)
  - [ ] simple registry HTTP API DEP - *informative* (@pfrazee)
  - [ ] wire-protocol - *standard* (@pfrazee, @mafintosh review)
  - [ ] hyperdb - *standard* (@bnewbold, @mafintosh review)
  - [ ] multi-writer - *standard* (@bnewbold, @mafintosh review)
  - [ ] nomenclature - *informative* (@joehand, WG review)
  - [ ] discovery - *informative* (@taravancil/@pfrazee, @mafintosh review)
  - [ ] hyperdrive - *standard* (@pfrazee, @mafintosh review)
  - [ ] SLEEP - *standard*
* Network updates (from prev meeting)
  - [ ] Change DNS to use datprotocol.com (@joehand to ping @mafintosh to ping joe about it)
      - [ ] update dat-swarm-defaults
      - [ ] change DNS (joe owns datprotocol.com)
      - [ ] other tasks (?)
* Heartbeat issue (https://github.com/datprotocol/DEPs/issues/18)
    - [ ] mafintosh want to implement bnewbold idea

**Comment by joehand** [comment]
Draft PR for the security issue template: https://github.com/datproject/dat/pull/972
