### ISSUE TITLE
Action Items - Meeting #9 (2 May)

### ISSUE THREAD

**Issue by pfrazee** [datprotocol/working-group#20]
[Meeting notes](https://github.com/datprotocol/working-group/blob/master/meeting-notes/08-18apr2018.md)

* DEPs
  - [x] Dat DNS DEP - *standard* (@pfrazee)
  - [x] wire-protocol - *standard* (@pfrazee, @mafintosh review)
  - [x] hyperdb - *standard* (@bnewbold, @mafintosh review)
  - [ ] multi-writer - *standard* (@bnewbold, @mafintosh review)
  - [ ] nomenclature - *informative* (@joehand, WG review)
  - [ ] discovery - *informative* (@taravancil/@pfrazee, @mafintosh review)
  - [ ] hyperdrive - *standard* (@pfrazee, @mafintosh review)
  - [ ] SLEEP - *standard*
* Security:
    - [ ] Add security email to the websites (@joehand, @pfrazee/@taravancil)
    - [ ] readmes of dat cli, dat-node (@joehand); beaker (@pfrazee/@taravancil)
* Heartbeat issue (https://github.com/datprotocol/DEPs/issues/18)
    - [ ] mafintosh want to implement bnewbold idea
* DNS
  - [x] update dat docs with datland-swarm-defaults (@joehand)
* datprotocol/DEPs#25 (Dat DNS DEP)
  - [x] add privacy/security section (@pfrazee)
  - [x] update the TXT record format (@pfrazee)
* datprotocol/DEPs#3 (HyperDB DEP)
  - [x] make final changes based on feedback (@bnewbold)
  - [x] merge and publish as draft (@bnewbold)
* hypercore data-structure identification headers
  - [ ] try to finish discussion https://github.com/datprotocol/DEPs/issues/13 (@mafintosh, @bnewbold, all)

**Comment by bnewbold** [comment]
HyperDB is merged (my checkbox clicks don't ever seem to work on github.com)
