### ISSUE TITLE
 Action Items - Meeting #11 (6 June)

### ISSUE THREAD

**Issue by joehand** [datprotocol/working-group#23]
### Action items
Dat Protocol WG meeting **[06 June 2018]** ([meeting notes](https://github.com/datprotocol/working-group/blob/master/meeting-notes/11-06June2018.md))

* Hypercore data-structure headers
    * DEP: all known data structures should follow the 1st message is a header message structure
    * Message looks like this {protocol: stringName}
    - [x] @mafintosh
* dat-dns
    - [x] Implement updated dat-dns in CLI (@joehand)
- [x] merge draft of session data DEP (@pfrazee)
* Place to list extensions
    - [x] short proposal where to list (@pfrazee)
- [x] discuss ephemeral msg extension in DEP PR (@mafintosh, @pfrazee)

**Comment by joehand** [comment]
dat-dns update in CLI: https://github.com/datproject/dat-link-resolve/pull/9

**Comment by pfrazee** [comment]
Hypercore headers:

 - https://github.com/mafintosh/hypertrie/blob/master/schema.proto#L2
 - https://github.com/mafintosh/hyperdrive/blob/master/schema.proto#L2
 - https://github.com/mafintosh/hyperdb/blob/master/schema.proto#L25
