### ISSUE TITLE
 Upcoming Meeting Agenda - 20th June 2018

### ISSUE THREAD

**Issue by joehand** [datprotocol/working-group#24]
Please comment with proposed agenda items (start comment with **AGENDA ITEM**). When a comment gets a +1 from a WG member, then we will add it to the agenda.

### Proposed Agenda

- Review previous action items
* discuss multi-writer DEP (datprotocol/DEPs#10)
* discuss ephemeral messaging extension DEP (datprotocol/DEPs#28)
* process for updating hyperdb DEP with recent implementation changes (deleted flag, protocol type header). 
* Discuss integrating an anonymity layer like tor or i2p with dat. Some community members are concerned that we haven't prioritized it yet. What do potential solutions look like? Can we accomplish it with the people and resources we have available? If so, when and how?

### Meetings Prep

- Before Meeting:
  - [ ] Create new meeting notes [file from template](https://github.com/datprotocol/working-group/blob/master/meeting-notes/NUM-DAYMONTHYEAR-TEMPLATE.md)
  - [ ] Add links to: agenda discussion, previous meeting action items, previous meeting notes
  - [ ] Put agenda in notes
- After Meeting:
  - [ ] Make [Action Items Issue](https://github.com/datprotocol/working-group/issues/new?template=meeting_actions.md), list action items
  - [ ] Commit meeting notes to working-group repo
  - [ ] Make [New Meeting Agenda Issue](https://github.com/datprotocol/working-group/issues/new?template=meeting_agenda.md)

**Comment by bnewbold** [comment]
**AGENDA ITEM:** discuss multi-writer DEP (https://github.com/datprotocol/DEPs/pull/10)

**Comment by pfrazee** [comment]
**AGENDA ITEM**: discuss ephemeral messaging extension DEP (https://github.com/datprotocol/DEPs/pull/28)

**Comment by pfrazee** [comment]
**AGENDA ITEM**: reader privacy

**Comment by taravancil** [comment]
**AGENDA ITEM**: Discuss integrating an anonymity layer like tor or i2p with dat. Some community members are concerned that we haven't prioritized it yet. What do potential solutions look like? Can we accomplish it with the people and resources we have available? If so, when and how?

**Comment by pfrazee** [comment]
**AGENDA ITEM**: Discuss https://github.com/datprotocol/website/pull/14
