### ISSUE TITLE
Action Items - Meeting #12 (20 June)

### ISSUE THREAD

**Issue by pfrazee** [datprotocol/working-group#26]
## ACTION ITEMS

* dat-dns node v6 support:
    - [x] @pfrazee figure out something for async/await support in node v6
* write a "data structure header" DEP
    - [x] (@pfrazee and @mafintosh)
* extensions listing:
    - [x] update language on website (@pfrazee)
    - [ ] add extension process note to DEP repo (@pfrazee)
    - [x] link to DEP repo extension process on website  (@pfrazee)
    - [x] merge website PR (@pfrazee)
* privacy concerns:
    - [ ] test out i2p/tor and read up on protocol (@pfrazee)
    - [x] prioritize having beaker leave a swarm when you leave the page (@pfrazee)
    - [x] reach out to folks who brought up concerns (@joehand)
    - [x] enumerate options for short-term
    - [x] docs updates, clarify (@joehand)
* DEP updates
    - [x] get multiwriter ready for vote (@bnewbold)
    - [ ] get hyperdb update ready for vote (@bnewbold)
* Ephemeral message extension DEP 
    - [x] add a soft message-size limit of 2kb (@pfrazee)

**Comment by bnewbold** [comment]
I just made multiwriter changes this morning; I forgot about hyperdb updates and haven't done those yet.
