### ISSUE TITLE
Upcoming Meeting Agenda - 18th July 2018

### ISSUE THREAD

**Issue by pfrazee** [datprotocol/working-group#27]
Please comment with proposed agenda items (start comment with **AGENDA ITEM**). When a comment gets a +1 from a WG member, then we will add it to the agenda.

### Proposed Agenda

* Review last meeting/action items
* Re-orient the WG after the break
* Discuss next steps for security issue https://github.com/datproject/security-discussion/issues/1

### Meetings Prep

- Before Meeting:
  - [x] Create new meeting notes [file from template](https://github.com/datprotocol/working-group/blob/master/meeting-notes/NUM-DAYMONTHYEAR-TEMPLATE.md)
  - [x] Add links to: agenda discussion, previous meeting action items, previous meeting notes
  - [x] Put agenda in notes
- After Meeting:
  - [x] Make [Action Items Issue](https://github.com/datprotocol/working-group/issues/new?template=meeting_actions.md), list action items
  - [x] Commit meeting notes to working-group repo
  - [ ] Make [New Meeting Agenda Issue](https://github.com/datprotocol/working-group/issues/new?template=meeting_agenda.md)

**Comment by joehand** [comment]
Discuss next steps for security issue https://github.com/datproject/security-discussion/issues/1
