### ISSUE TITLE
Action Items - Meeting #13 (6 July)

### ISSUE THREAD

**Issue by pfrazee** [datprotocol/working-group#28]
## ACTION ITEMS

* extentions
  - [ ] add extension process note to DEP repo (@pfrazee)
* hyperdb DEP
  - [ ] get hyperdb update ready for vote (@bnewbold)
* privacy/security
  - [ ] prioritize having beaker leave a swarm when you leave the page (@pfrazee)
  - [ ] docs update (@joehand)
  - [ ] OTF red team audit application (@joehand)
  - [ ] try using dat over tor (@pfrazee)
  - [ ] benchmark over wan (if tor works, @pfrazee)
  - [ ] experiment and write up tor experiements (@bnewbold)
  - [ ] organize hack/meet up with tor folks at dweb (@bnewbold)

**Comment by bnewbold** [comment]
As a reminder, next WG meeting is in a week (Wed, Aug 15th). We didn't make progress on action items at the last meeting, and everybody has (presumably) be swamped with travel and conferences until now, but it would be great to hit some of these for next week.
