### ISSUE TITLE
Upcoming Meeting Agenda - 12 September 2018

### ISSUE THREAD

**Issue by pfrazee** [datprotocol/working-group#30]
Please comment with proposed agenda items (start comment with **AGENDA ITEM**). When a comment gets a +1 from a WG member, then we will add it to the agenda.

### Proposed Agenda

 - Make sure we have a DEP for the upcoming hyperdrive trie-structure update
 - MOSS grant/ DEP updates related to implementation guide
 - Security issues

### Meetings Prep

- Before Meeting:
  - [ ] Create new meeting notes [file from template](https://github.com/datprotocol/working-group/blob/master/meeting-notes/NUM-DAYMONTHYEAR-TEMPLATE.md)
  - [ ] Add links to: agenda discussion, previous meeting action items, previous meeting notes
  - [ ] Put agenda in notes
- After Meeting:
  - [ ] Make [Action Items Issue](https://github.com/datprotocol/working-group/issues/new?template=meeting_actions.md), list action items
  - [ ] Commit meeting notes to working-group repo
  - [ ] Make [New Meeting Agenda Issue](https://github.com/datprotocol/working-group/issues/new?template=meeting_agenda.md)

**Comment by bnewbold** [comment]
I'm going to have to skip this week: moving and busy through the weekend. Not much to report.

**Comment by pfrazee** [comment]
We elected to cancel the meeting and push to the next time

**Comment by pfrazee** [comment]
Make sure we have a DEP for the upcoming hyperdrive trie-structure update

**Comment by pfrazee** [comment]
Make progress on the outstanding security report

**Comment by pfrazee** [comment]
MOSS grant/ DEP updates related to implementation guide
