### ISSUE TITLE
Upcoming Meeting Agenda - 26 September 2018

### ISSUE THREAD

**Issue by pfrazee** [datprotocol/working-group#31]
Please comment with proposed agenda items (start comment with **AGENDA ITEM**). When a comment gets a +1 from a WG member, then we will add it to the agenda.

### Proposed Agenda

 - AGENDA ITEM: Discuss new Hyperswarm project https://pfrazee.hashbase.io/blog/hyperswarm
 - AGENDA ITEM: Should we deploy hyperdrive-v2 with a simplified trie structure, or with hyperdb single-writer?
 - AGENDA ITEM: "Follow redirects in DNS?" datprotocol/DEPs#40 TL;DR: should we allow HTTP redirects of .well-known/dat? In particular in handling of www.example.tld vs. example.tld. Alternative is to require direct response on both like Let's Encrypt.
 - AGENDA ITEM: "Added functions for sign/verify to DEP 0002" datprotocol/DEPs#41. TL;DR: include more Javascript+libsodium code in a DEP as a clarification. My dispensation is to merge this PR, and also expand the english language with reference to specific (crypto) RFCs and what is getting hashed signed.

### Meetings Prep

- Before Meeting:
  - [x] Create new meeting notes [file from template](https://github.com/datprotocol/working-group/blob/master/meeting-notes/NUM-DAYMONTHYEAR-TEMPLATE.md)
  - [x] Add links to: agenda discussion, previous meeting action items, previous meeting notes
  - [x] Put agenda in notes
- After Meeting:
  - [x] Make [Action Items Issue](https://github.com/datprotocol/working-group/issues/new?template=meeting_actions.md), list action items
  - [x] Commit meeting notes to working-group repo
  - [x] Make [New Meeting Agenda Issue](https://github.com/datprotocol/working-group/issues/new?template=meeting_agenda.md)

**Comment by bnewbold** [comment]
@pfrazee is there more context for the simplified trie structure mentioned above?

**Comment by bnewbold** [comment]
Two brief proto issues that are more than 2 weeks old and should be resolved:

- "Follow redirects in DNS?" https://github.com/datprotocol/DEPs/issues/40 TL;DR: should we allow HTTP redirects of `.well-known/dat`? In particular in handling of `www.example.tld` vs. `example.tld`. Alternative is to require direct response on both like Let's Encrypt.

"Added functions for sign/verify to DEP 0002" https://github.com/datprotocol/DEPs/pull/41. TL;DR: include more Javascript+libsodium code in a DEP as a clarification. My dispensation is to merge this PR, and also expand the english language with reference to specific (crypto) RFCs and what is getting hashed signed.

**Comment by pfrazee** [comment]
@bnewbold we'll discuss it in the meeting. Basically, @mafintosh factored out the trie-structure and was thinking it might be easier to deploy that now for a quick perf gain.
