### ISSUE TITLE
Upcoming Meeting Agenda - 24 October 2018

### ISSUE THREAD

**Issue by pfrazee** [datprotocol/working-group#34]
Please comment with proposed agenda items (start comment with **AGENDA ITEM**). When a comment gets a +1 from a WG member, then we will add it to the agenda.

### Proposed Agenda

...

### Meetings Prep

- Before Meeting:
  - [ ] Create new meeting notes [file from template](https://github.com/datprotocol/working-group/blob/master/meeting-notes/NUM-DAYMONTHYEAR-TEMPLATE.md)
  - [ ] Add links to: agenda discussion, previous meeting action items, previous meeting notes
  - [ ] Put agenda in notes
- After Meeting:
  - [ ] Make [Action Items Issue](https://github.com/datprotocol/working-group/issues/new?template=meeting_actions.md), list action items
  - [ ] Commit meeting notes to working-group repo
  - [ ] Make [New Meeting Agenda Issue](https://github.com/datprotocol/working-group/issues/new?template=meeting_agenda.md)

**Comment by bnewbold** [comment]
I will be on a plane for this week's WG :crying_cat_face:

**Comment by pfrazee** [comment]
Do we want to reschedule? I'm fine moving it a day.

**Comment by pfrazee** [comment]
We've bumped the meeting to the next scheduled time.

**Comment by pfrazee** [comment]
Discuss and vote on https://github.com/datprotocol/DEPs/pull/47 (typo fixes)

**Comment by pfrazee** [comment]
Discuss https://github.com/datprotocol/DEPs/pull/43 (hypercore split resolution protocol)

**Comment by pfrazee** [comment]
Discuss https://github.com/datprotocol/DEPs/issues/45 (issues with the current DNS spec)

**Comment by yoshuawuyts** [comment]
I'm not partaking int he meeting, but it's probably worth mentioning I've started work on an "implementers guide to Dat" on https://github.com/datprotocol/book. A current snapshot can be viewed here: https://pierd.github.io/book/getting-started.html.
