### ISSUE TITLE
Upcoming Meeting Agenda - 7 November 2018

### ISSUE THREAD

**Issue by pfrazee** [datprotocol/working-group#36]
Please comment with proposed agenda items (start comment with **AGENDA ITEM**). When a comment gets a +1 from a WG member, then we will add it to the agenda.

### Proposed Agenda

...

### Meetings Prep

- Before Meeting:
  - [ ] Create new meeting notes [file from template](https://github.com/datprotocol/working-group/blob/master/meeting-notes/NUM-DAYMONTHYEAR-TEMPLATE.md)
  - [ ] Add links to: agenda discussion, previous meeting action items, previous meeting notes
  - [ ] Put agenda in notes
- After Meeting:
  - [ ] Make [Action Items Issue](https://github.com/datprotocol/working-group/issues/new?template=meeting_actions.md), list action items
  - [ ] Commit meeting notes to working-group repo
  - [ ] Make [New Meeting Agenda Issue](https://github.com/datprotocol/working-group/issues/new?template=meeting_agenda.md)

**Comment by pfrazee** [comment]
We all flaked on the 21st. We'll hit what we can without you on the 5th.

**Comment by martinheidegger** [comment]
Next?

**Comment by pfrazee** [comment]
Yeah we couldn't run the 5th either, not enough attendance. If maf and bnewbold can make it to the meeting on the 19th, we can have the meeting

**Comment by pfrazee** [comment]
AGENDA ITEM

Discuss this versioning proposal and write down our plans https://github.com/datprotocol/DEPs/issues/54

**Comment by pfrazee** [comment]
AGENDA ITEM

Discuss the Intent DEP https://github.com/datprotocol/DEPs/pull/53

**Comment by yoshuawuyts** [comment]
Is there a meeting later today? I'd love to join in if possible.

**Comment by martinheidegger** [comment]
Didn't sleep in a while and can't hold it back anymore, sorry for missing out on you guys. But tomorrow: https://github.com/dat-land/comm-comm/issues/1
