### ISSUE TITLE
Upcoming Meeting Agenda - 16 November 2019

### ISSUE THREAD

**Issue by pfrazee** [datprotocol/working-group#38]
Please comment with proposed agenda items (start comment with **AGENDA ITEM**). When a comment gets a +1 from a WG member, then we will add it to the agenda.

### Proposed Agenda

...

### Meetings Prep

- Before Meeting:
  - [ ] Create new meeting notes [file from template](https://github.com/datprotocol/working-group/blob/master/meeting-notes/NUM-DAYMONTHYEAR-TEMPLATE.md)
  - [ ] Add links to: agenda discussion, previous meeting action items, previous meeting notes
  - [ ] Put agenda in notes
- After Meeting:
  - [ ] Make [Action Items Issue](https://github.com/datprotocol/working-group/issues/new?template=meeting_actions.md), list action items
  - [ ] Commit meeting notes to working-group repo
  - [ ] Make [New Meeting Agenda Issue](https://github.com/datprotocol/working-group/issues/new?template=meeting_agenda.md)

**Comment by joehand** [comment]
AGENDA ITEM: where to post duncanvt's "How Dat Works" (and whether it should live on github.com/datproject or github.com/datprotocol)
