### ISSUE TITLE
Upcoming Meeting Agenda - 7 Feb 2017

### ISSUE THREAD

**Issue by joehand** [datprotocol/working-group#4]
Please comment with proposed agenda items (start comment with **AGENDA ITEM**). Once a comment gets a +1 then I'll update this comment to include on the agenda.

**Note: this meeting may be rescheduled. Bryan is not available. Karissa/Joe/Danielle will only be available for a short time.**

### Proposed Agenda

- Merge DEP 1 (datprotocol/DEPs#2) under Draft status (PAUL)
- Report status of all DEPs assigned at last meeting (PAUL)

**Comment by joehand** [comment]
**AGENDA ITEM**

Leftover from last meeting (proposed by @bnewbold)

- **BRYAN** multi-writer API ergonomics (eg, making single-writer case simple)<sup id="a1">[1](#f1)</sup>


##### Footnotes

<b id="f1">1</b> I was primarily thinking of API users. This is referring to the conversation we had about `get()` returning an array of values (potentially one from each writer, if there was a conflict), and leaving disambiguation to API callers. I think this might be reasonable from a modularity standpoint, but want to make sure that helpers exist somewhere so high-level app developers don't need to invent a disambiguation solution every time (unless they want to), or worse, do something trivial like take the first element of the array, which would work for single-writer but break in confusing ways later. [&#x21a9;](#a1)

**Comment by pfrazee** [comment]
AGENDA ITEM

Merge DEP 1 (https://github.com/datprotocol/DEPs/pull/2) under Draft status

**Comment by pfrazee** [comment]
AGENDA ITEM

Report status of all DEPs assigned at last meeting
