### ISSUE TITLE
Upcoming Meeting: May 8th, 2019

### ISSUE THREAD

**Issue by bnewbold** [datprotocol/working-group#51]
Please comment with proposed agenda items (start comment with **AGENDA ITEM**). When a comment gets a +1 from a WG member, then we will add it to the agenda.

### Proposed Agenda

- ...

### Meetings Prep

- Before Meeting:
  - [x] Create new meeting notes [file from template](https://github.com/datprotocol/working-group/blob/master/meeting-notes/NUM-DAYMONTHYEAR-TEMPLATE.md)
  - [x] Add links to: agenda discussion, previous meeting action items, previous meeting notes
  - [x] Put agenda in notes
- After Meeting:
  - [x] Make [Action Items Issue](https://github.com/datprotocol/working-group/issues/new?template=meeting_actions.md), list action items
  - [x] Commit meeting notes to working-group repo
  - [x] Make [New Meeting Agenda Issue](https://github.com/datprotocol/working-group/issues/new?template=meeting_agenda.md)

**Comment by bnewbold** [comment]
@chartgerink requests we discuss version hashing (https://github.com/datprotocol/DEPs/issues/54)

**Comment by RangerMauve** [comment]
We should discuss formalizing how the meetings should be organized (and by who) as well as reducing some of the boilerplate.

**Comment by RangerMauve** [comment]
It'd be cool if more people in the Dat ecosystem had a roadmap for what they're working on so that the community can be up to date.

Sort of like https://github.com/datproject/planning/issues/8 and https://github.com/datproject/planning/issues/7

**Comment by RangerMauve** [comment]
Is there a writeup somewhere on how the new multiwriter (union mounts) thing is supposed to work? It's not based on hyperdb, right?

**Comment by karissa** [comment]
adding agenda item:  having at least a general quick overview of what people are working on (e.g., multiwiter) and how it is designed would be nice so people out of the loop like me rangermauve jhand etc can answer questions at dtn and in the #dat channel

**Comment by RangerMauve** [comment]
Discuss this: https://github.com/datprotocol/DEPs/issues/60

**Comment by RangerMauve** [comment]
What number meeting was this? 😅

**Comment by RangerMauve** [comment]
Props to whoever set up the templates!
