### ISSUE TITLE
Upcoming Meeting Agenda - 21 Feb 2017

### ISSUE THREAD

**Issue by pfrazee** [datprotocol/working-group#6]
Please comment with proposed agenda items (start comment with **AGENDA ITEM**). Once a comment gets a +1 then I'll update this comment to include on the agenda.

**Comment by pfrazee** [comment]
**AGENDA ITEM**

Leftover from last meeting (proposed by @bnewbold)

- **BRYAN** multi-writer API ergonomics (eg, making single-writer case simple)<sup id="a1">[1](#f1)</sup>


##### Footnotes

<b id="f1">1</b> I was primarily thinking of API users. This is referring to the conversation we had about `get()` returning an array of values (potentially one from each writer, if there was a conflict), and leaving disambiguation to API callers. I think this might be reasonable from a modularity standpoint, but want to make sure that helpers exist somewhere so high-level app developers don't need to invent a disambiguation solution every time (unless they want to), or worse, do something trivial like take the first element of the array, which would work for single-writer but break in confusing ways later. [&#x21a9;](#a1)

**Comment by pfrazee** [comment]
**AGENDA ITEM**

Review any nomenclature questions

**Comment by joehand** [comment]
Vote on DEP-0001 to move from draft to approved.

**Comment by pfrazee** [comment]
Vote to move the Hypercore DEP to draft status

**Comment by joehand** [comment]
Regarding: 

>  BRYAN multi-writer API ergonomics (eg, making single-writer case simple)1

Bryan explained it to me at IA and there are kind of two issues, if I understand. One, that may be good to discuss, is whether we want to prioritize getting hyperdb (without multiwriter) into the protocol before tackling multiwriter.
