### ISSUE TITLE
Upcoming Meeting: July 31st 2019

### ISSUE THREAD

**Issue by RangerMauve** [datprotocol/working-group#60]
Please comment with proposed agenda items (start comment with **AGENDA ITEM**). When a comment gets a +1 from a WG member, then we will add it to the agenda.

### Proposed Agenda

- ...

### Meetings Prep

- Before Meeting:
  - [x] Create new meeting notes [file from template](https://github.com/datprotocol/working-group/blob/master/meeting-notes/NUM-DAYMONTHYEAR-TEMPLATE.md)
  - [x] Add links to: agenda discussion, previous meeting action items, previous meeting notes
  - [x] Put agenda in notes
- After Meeting:
  - [x] Make [Action Items Issue](https://github.com/datprotocol/working-group/issues/new?template=meeting_actions.md), list action items
  - [x] Commit meeting notes to working-group repo
  - [ ] Make [New Meeting Agenda Issue](https://github.com/datprotocol/working-group/issues/new?template=meeting_agenda.md)

**Comment by RangerMauve** [comment]
* Talk about extensions and how they relate to the daemon and Beaker.
* Talk about grouping hypercores together (for use cases using multifeed)
* Talk about more fine grained control over networking https://github.com/cabal-club/cabal-cli/issues/113

**Comment by RangerMauve** [comment]
Talk about use of MDNS in hyperswarm https://github.com/hyperswarm/discovery/issues/7

**Comment by RangerMauve** [comment]
Talk about backwards compatibility with old hyperdrive

**Comment by pfrazee** [comment]
- Share [this protocol dev roadmap](https://hackmd.io/VamhcsPjTcCvBgn4Sfr_0Q) and make sure everybody's on the same page

**Comment by substack** [comment]
adding an `optional boolean ack` field to HAVE messages https://github.com/mafintosh/hypercore/pull/215#issuecomment-515804589

**Comment by noffle** [comment]
I'd like to try to better understand Dat SDK's specific needs around multifeed/corestore/etc, which I'm kinda fuzzy on still.

**Comment by RangerMauve** [comment]
@noffle Would you mind if we discussed the SDK thing outside of the working group call? I'm worried about time for some of these other things.

**Comment by RangerMauve** [comment]
Also, from @karissa

> hey all, for the next meeting I'd like to put on the agenda discussing governance of the dat foundation and how we can adopt (or avoid) models from other open source foundations (e.g., linux, node, raspberry pi, etc).. I'd like to transition out of what is now a narrowly defined 'leadership' role and have a transparent voting collective make decisions by January, so we have time to make this transition and work
14:27 together to craft a governance model that we all like
14:28 btw: the 'foundation' decides what to do with donations

**Comment by RangerMauve** [comment]
Also, to save time I'd like to put off some of the [technical stuff](https://github.com/datprotocol/working-group/issues/60#issuecomment-510615032) I wanted to discuss until next time.

**Comment by noffle** [comment]
@RangerMauve that's fine, yes!

I'd also like to bring up hypercore performance when *many* (hundreds) of cores are being loaded and replicated.

**Comment by RangerMauve** [comment]
Also, it'd be nice to quickly peek at this [replication management proposal](https://gist.github.com/RangerMauve/de1004077fa90a2ed219b48c8a49939b) to integrate with the daemon / SDK.
