### ISSUE TITLE
Upcoming Meeting: #29 August 14th, 2019

### ISSUE THREAD

**Issue by RangerMauve** [datprotocol/working-group#63]
Please comment with proposed agenda items (start comment with **AGENDA ITEM**). When a comment gets a +1 from a WG member, then we will add it to the agenda.

### Proposed Agenda

- What's everyone been up to?

### Meetings Prep

- Before Meeting:
  - [x] Create new meeting notes [file from template](https://github.com/datprotocol/working-group/blob/master/meeting-notes/NUM-DAYMONTHYEAR-TEMPLATE.md)
  - [x] Add links to: agenda discussion, previous meeting action items, previous meeting notes
  - [x] Put agenda in notes
- After Meeting:
  - [x] Make [Action Items Issue](https://github.com/datprotocol/working-group/issues/new?template=meeting_actions.md), list action items
  - [x] Commit meeting notes to working-group repo
  - [x] Make [New Meeting Agenda Issue](https://github.com/datprotocol/working-group/issues/new?template=meeting_agenda.md)

**Comment by RangerMauve** [comment]
* Talk about more fine grained control over networking cabal-club/cabal-cli#113
* Talk about use of MDNS in hyperswarm hyperswarm/discovery#7

**Comment by RangerMauve** [comment]
- talk about multiwriter. Karissa and some people from cobox put together this: https://github.com/coboxcoop/peerfs which seems to be working.
- Dual licensing the SDK with proceeds going to the Dat project.

**Comment by joehand** [comment]
* Talk about datprotocol.com and dat website updates.

![Dat Project sitemaps](https://user-images.githubusercontent.com/684965/63033982-6105e600-be6d-11e9-958e-2ba85e8e438f.png)

**Comment by noffle** [comment]
I'd like to briefly discuss exposing more detailed "replication progress" information!
