### ISSUE TITLE
Upcoming Meeting #31 September 11th, 2019

### ISSUE THREAD

**Issue by RangerMauve** [datprotocol/working-group#67]
Please comment with proposed agenda items (start comment with **AGENDA ITEM**). When a comment gets a +1 from a WG member, then we will add it to the agenda.

### Proposed Agenda

* catch up
* Talk about more fine grained control over networking cabal-club/cabal-cli#113
* Dual licensing the SDK with proceeds going to the Dat project.
* ideas for "files as files" in new hyperdrive
* overview of plans for multiwriter

### Meetings Prep

- Before Meeting:
  - [x] Create new meeting notes [file from template](https://github.com/datprotocol/working-group/blob/master/meeting-notes/NUM-DAYMONTHYEAR-TEMPLATE.md)
  - [x] Add links to: agenda discussion, previous meeting action items, previous meeting notes
  - [x] Put agenda in notes
- After Meeting:
  - [ ] Make [Action Items Issue](https://github.com/datprotocol/working-group/issues/new?template=meeting_actions.md), list action items
  - [ ] Commit meeting notes to working-group repo
  - [ ] Make [New Meeting Agenda Issue](https://github.com/datprotocol/working-group/issues/new?template=meeting_agenda.md)

**Comment by karissa** [comment]
Agenda item:  CLI roadmap

**Comment by RangerMauve** [comment]
@mafintosh offered to do a deep dive on the new protocol changes
