### ISSUE TITLE
Upcoming Meeting Agenda - 7 Mar 2017

### ISSUE THREAD

**Issue by pfrazee** [datprotocol/working-group#8]
Please comment with proposed agenda items (start comment with AGENDA ITEM). Once a comment gets a +1 then I'll update this comment to include on the agenda.

**Comment by joehand** [comment]
decide on block vs entry discussion

**Comment by joehand** [comment]
AGENDA ITEM: nomenclature ambiguity whether SLEEP means individual files or the collection of files hypercore uses

**Comment by pfrazee** [comment]
AGENDA ITEM: how to handle breaking changes, specifically how the version used by a hypercore/drive is signalled

**Comment by joehand** [comment]
Notes at https://github.com/datprotocol/working-group/blob/master/meeting-notes/05-07mar2018.md
