### ISSUE TITLE
Upcoming Meeting Agenda - 21 Mar 2017

### ISSUE THREAD

**Issue by pfrazee** [datprotocol/working-group#9]
Please comment with proposed agenda items (start comment with AGENDA ITEM). Once a comment gets a +1 then I'll update this comment to include on the agenda.

### Proposed Agenda

* AGENDA ITEM: standard hypercore header to identify protocol and protocol version. Should it just be conventional? Should it be extra data outside the feed/merkle-tree? Should it be large enough to move dat.json metadata into it?
* AGENDA ITEM: standardizing the protocol for registries (dat publish)
* AGENDA ITEM: I'd like to invite [@andrewosh](https://github.com/andrewosh) to join the WG. He has deep knowledge of the internals and built multiple interesting modules on top

### Meetings Prep

- Before Meeting:
  - [ ] Create new meeting notes [file from template](https://github.com/datprotocol/working-group/blob/master/meeting-notes/NUM-DAYMONTHYEAR-TEMPLATE.md)
  - [ ] Add links to: agenda discussion, previous meeting action items, previous meeting notes
  - [ ] Put agenda in notes
- After Meeting:
  - [ ] Make [Action Items Issue](https://github.com/datprotocol/working-group/issues/new?template=meeting_actions.md), list action items
  - [ ] Commit meeting notes to working-group repo
  - [ ] Make [New Meeting Agenda Issue](https://github.com/datprotocol/working-group/issues/new?template=meeting_agenda.md)

**Comment by pfrazee** [comment]
AGENDA ITEM: wire protocol versioning

**Comment by pfrazee** [comment]
AGENDA ITEM: standard hypercore header. Should it just be conventional? Should it be extra data outside the feed/merkle-tree? Should it be large enough to move dat.json metadata into it?

**Comment by pfrazee** [comment]
AGENDA ITEM: standardizing the protocol for registries (dat publish)

**Comment by mafintosh** [comment]
AGENDA ITEM: I'd like to invite @andrewosh to join the WG. He has deep knowledge of the internals and built multiple interesting modules on top
